config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :abouts 
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :users, optional: true
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         has_many :categories
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @categories = Category.new
  end
  def create 
    @categories = Category.new(categories_params)
    if (@categories.save!)
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @categories=Category.find_by_slug(params[:id])
  end
  def update
    @categories=Category.find(params[:id])
    if @categories.update(categories_params)
      redirect_to categories_path
    else 
      render :update
    end
  end
  def destroy
    @categories=Category.find(params[:id])
    @categories.destroy
    redirect_to categories_path
  end
  private 
  def categories_params
    params.require(:category).permit(:name)
 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @products = Product.all
    @categories = Category.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create 
    @product = Product.new(products_params)

    if (@product.save)

      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(products_params)
      redirect_to products_path
    else 
      render :update
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def products_params
    params.require(:product).permit(:name, :contents, :description, :image, :price, :category_id)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
 <!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="">
  <%= favicon_link_tag asset_path('logo.png') %>
  <title> Chizz Fast & Burger </title>

  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <link href="css/font-awesome.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="css/style.css" rel="stylesheet" />
  <link href="css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <div class="bg-box">
      <%= image_tag "hero-bg.jpg" %>
    </div>
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <%= link_to root_path, class:"navbar-brand" do %>
            <span>
              <%= image_tag "logo.png", style:"max-width: 60px" %>
            </span>
          <%end%>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ml-auto ">
              <li class="nav-item active">
                <%= link_to "Anasayfa", root_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Menü", products_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Hakkımızda", abouts_path, class:"nav-link"%>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
  </div>

  <section class="book_section layout_padding">
    <div class="container">
        <h2 class="text-center mb-4">Tüm Kategoriler</h2>

        <div class="row justify-content-center">
          <div class="col-md-6">
            <table class="table">
              <thead>
                  <tr>
                  <th scope="col">Kategori Adı</th>
                  <th scope="col"><span class="float-right">İşlemler</span></th>
                  </tr>
              </thead>
              <tbody>
                  
              <% @categories.each do |category|%>
                <tr>
                  <td><%= category.name %></td>
                  <td class="d-flex justify-content-end">
                    <%= link_to "Güncelle", edit_category_path(category.id), class:"btn btn-sm btn-info", :method => "get"%>
                    <%= button_to "Sil", category_path(category.id), class:"btn btn-sm btn-danger ml-2", method: :delete %>
                  </td>
                </tr>
              <% end %>
                  
              </tbody>
            </table>
            
            <div>
              <div>
                  <%= link_to "Yeni Kategori Ekle", new_category_path, class:"btn btn-sm btn-success pull-right"%>
              </div>
            </div>

          </div>
        </div>

        









        
    </div>
  </section>
  
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              İletişim
            </h4>
            <div class="contact_link_box">
              <a href="https://goo.gl/maps/ZAu4peM8dqsEzmoWA">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Ataşehir, İmam Efendi Blv. no: 38/B, 23100 Merkez/Elazığ
                </span>
              </a>
              <a href="tel:+904242473253">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  0(424) 247 32 53
                </span>
              </a>
              <a href="mailto:chizzburger22@gmail.com">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  chizzburger22@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              <%= image_tag "logo.png", style:"max-width: 60px;"%>
            </a>
            <p>
              Burgerin en ateşli hali. Footer alt bilgi açıklama metin kutusu
            </p>
            <div class="footer_social">
              <a href="" style="color: black">
                <i class="fa-brands fa-facebook"></i>
              </a>
              <a href="">
                <i class="fa-brands fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="instagr.am/chizz_burger_food_23">
                <i class="fa-brands fa-instagram" aria-hidden="true"></i>
              </a>
              <%= link_to root_path do%>
                <i class="fa-brands fa-pinterest" aria-hidden="true"></i>
              <%end%>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Çalışma Saatlerimiz
          </h4>
          <p>
            Haftanın her günü
          </p>
          <p>
            12.00 - 00.00
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          Chizz Burger & Food &copy; <span id="displayYear"></span> Tüm Hakları Saklıdır.<br>
          Uygulama Tasarım | <a href="https://instagr.am/ufakbeg">iOTA.</a>
        </p>
      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0-beta1/js/bootstrap.min.js" integrity="sha512-Hqe3s+yLpqaBbXM6VA0cnj/T56ii5YjNrMT9v+us11Q81L0wzUG0jEMNECtugqNu2Uq5MSttCg0p4KK0kCPVaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
</body>

</html>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/_footer.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/js/bootstrap.bundle.min.js" integrity="sha512-ndrrR94PW3ckaAvvWrAzRi5JWjF71/Pw7TlSo6judANOFCmz0d+0YE+qIGamRRSnVzSvIyGs4BTtyFMm3MT/cg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/js/bootstrap.esm.min.js" integrity="sha512-OifclKQ3EcqFY0BeEriQwLgjjCNrpppz3ZlPkpj/n3WNGt40yraBf90OskicusnP4cFLO51uOTJAqEILpUmc4A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="/js/custom.js"></script>
<script src="/js/bootstrap.js"></script>
<script src="/js/jquery-3.4.1.min.js"></script>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="app/assets/stylesheet/style.css">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-grid.rtl.min.css" integrity="sha512-s6viiiLL/vlYgbXtO8pGrr42kjWwnVzT4/JNSIp2SaWujb2OfoevjdAqtNwkSwYg4KMzcLbHRIpHSMvXkw/d/w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-reboot.min.css" integrity="sha512-md3Ez3ol5kGsDp8o8HXvf5YgDnjBBpFXoLA/cyEjpkkMcppbLyfZLu32YuZ6N4KxoBFX6iLGpzmyq3U+LgyMjQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-reboot.rtl.min.css" integrity="sha512-aQFFIdPR6mmg6ir8+nduNGZZE5+JI7BBdfbaj0hlX43tQc0uGxxx0hqdAFXjpKVs5hbXCCcXsqnpl5GSH6LBEA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-utilities.min.css" integrity="sha512-GS872A1eDvydr4dV3Lz40gwF0skFGfS2NCMv12q+4PffqayDJ+Ffh8CO2xV6KQLJ5oTuA6Yjy4CcMcKMEG43Dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-utilities.rtl.min.css" integrity="sha512-9//hQXJwhp6cXp8GAnBjZDkONaYjbZciMWTOuMcsLx6qZORNV6GvfneJy70raNEu6hRt6VlsFNzz4UrdBNz7JA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0-beta1/css/bootstrap-grid.min.css" integrity="sha512-QWjMsIpO5eW4+c4ASTEaZ4+eZNZ4YTtSDiu167Rq1Eqw//WlO+rXo4OvZMpyW/ykbN5LFeXmN6N416OzmWo7fA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chizz Burger & Food</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'responsive', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="">
  <%= favicon_link_tag asset_path('logo.png') %>
  <title> Chizz Fast & Burger </title>

  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <link href="css/font-awesome.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="css/style.css" rel="stylesheet" />
  <link href="css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <div class="bg-box">
      <%= image_tag "hero-bg.jpg"%>
    </div>
    <header class="header_section">
      <div class="container">
        <nav class="navbar custom_nav-container d-flex justify-content-center">
          <%= link_to root_path do%>
            <%= image_tag "logo.png", style:"max-width: 55px; margin-right: 10px;"%>
          <%end%>
          <%= link_to root_path, class:"navbar-brand" do%>
            <span>
              Chizz Burger & Food
            </span>
          <%end%>

        </nav>
      </div>
    </header>
  </div>
  <div class="breadcumbs bg-light p-2 text-center">
    <% if user_signed_in?%>
      <%=link_to "Ürün Ekle",new_product_path, class:"btn btn-sm btn-success"%>
      <%=link_to "Kategori Ekle",new_category_path, class:"btn btn-sm btn-dark"%>
    <% end %>
  </div>


  <section class="food_section layout_padding" style="padding: 10px 0!important;">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>Menü</h2>
      </div>

      <div>
        <nav>

          <ul class="category_auto_flow text-center" id="nav-tab" role="tablist">
          <% @categories.each do |category| %>
            <li class="nav-link <%= @categories.first == category ? 'active' : ''%> " id="nav-<%=category.slug%>-tab" data-bs-toggle="tab" data-bs-target="#nav-<%=category.slug%>" type="button" role="tab" aria-controls="nav-<%=category.slug%>" aria-selected="true"><%=category.name%></li>

          <%end%>
            
          </ul>
        </nav>
        
        <% @categories.each do |category| %>
          <div class="tab-content" id="nav-tabContent">
          
            <div class="tab-pane filters-content <%= @categories.first == category ? 'active show' : ''%> " id="nav-<%=category.slug%>" role="tabpanel" aria-labelledby="nav-<%=category.slug%>-tab">
              <div class="row grid">
                <% category.products.each do |product| %>
                  <div class="col-sm-6 col-lg-4 mb-3">

                        <div class="card h-100 border-0 shadow text-center">
                          <div class="card-img-top">
                            <div class="embed-responsive embed-responsive-4by3" style="border: 10px solid #ff5f01;">
                              <div class="embed-responsive-item burger_img">
                                <%if product.image.attached?%>
                                  <%=image_tag product.image, class:"img-fluid w-100" %>
                                <%else%>
                                  Fotoğraf Bulunamadı.
                                <%end%>
                              </div>
                            </div>
                          </div>

                          <div class="card-body" style="background: #333; color: #f8f8f8;">
                            <h5>
                              <%= product.name %>
                            </h5>
                            <p class="p-detail-s">
                              <b>İçindekiler:</b>
                              <small><%=product.contents %></small>
                            </p>
                            <p class="p-detail-s">
                              <b>Açıklama:</b>
                              <small><%=product.description %></small>
                            </p>
                            <div class="options">
                              <h3>
                                <span style="background: #ff5f01; color: #333; border-radius: 5px;" class="p-1"><%= product.price %> &#8378;</span>
                              </h3>
                            </div>
                             <% if user_signed_in?%>
                              <div class="d-flex justify-content-center p-3 mt-3" style="background: #222; border-radius: 15px;">
                                  <%= link_to "Düzenle", edit_product_path(product.id), class:"btn btn-sm btn-success" %>
                                  <%= button_to 'Sil', product_path(product.id), method: :delete, data: {:confirm => 'Emin misiniz?'}, class:"btn btn-sm btn-danger ml-3" %>
                              </div>
                            <% end %>
                          </div>

                        </div>    
                                            
                  </div>
                <%end%>

                
              </div> 
            </div> 
          </div> 
        <%end%>
      </div>
    </div>
  </section>
  
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              İletişim
            </h4>
            <div class="contact_link_box">
              <a href="https://goo.gl/maps/ZAu4peM8dqsEzmoWA">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Ataşehir, İmam Efendi Blv. no: 38/B, 23100 Merkez/Elazığ
                </span>
              </a>
              <a href="tel:+904242473253">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  0(424) 247 32 53
                </span>
              </a>
              <a href="mailto:chizzburger22@gmail.com">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  chizzburger22@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              <%= image_tag "logo.png", style:"max-width: 60px;"%>
            </a>
            <p>
              Burgerin en ateşli hali. Footer alt bilgi açıklama metin kutusu
            </p>
            <div class="footer_social">
              <a href="" style="color: black">
                <i class="fa-brands fa-facebook"></i>
              </a>
              <a href="">
                <i class="fa-brands fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="instagr.am/chizz_burger_food_23">
                <i class="fa-brands fa-instagram" aria-hidden="true"></i>
              </a>
              <%= link_to root_path do%>
                <i class="fa-brands fa-pinterest" aria-hidden="true"></i>
              <%end%>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Çalışma Saatlerimiz
          </h4>
          <p>
            Haftanın her günü
          </p>
          <p>
            12.00 - 00.00
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          Chizz Burger & Food &copy; <span id="displayYear"></span> Tüm Hakları Saklıdır.<br>
          Uygulama Tasarım | <a href="https://instagr.am/ufakbeg">iOTA.</a>
        </p>
      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0-beta1/js/bootstrap.min.js" integrity="sha512-Hqe3s+yLpqaBbXM6VA0cnj/T56ii5YjNrMT9v+us11Q81L0wzUG0jEMNECtugqNu2Uq5MSttCg0p4KK0kCPVaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
</body>

</html>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>